### ISSUE TITLE
Error with createReobfPaperclipJar on forks

### ISSUE THREAD

**Issue by theomega24** [PaperMC/paperweight#120]
When running `gradle createReobfPaperclipJar --stacktrace` I get this error message: https://paste.lucko.me/qI4BIKEY1U

The build.gradle.kts, settings.gradle.kts, and patches can be found in the [Purpur ver/1.18 branch](https://github.com/pl3xgaming/Purpur/tree/ver/1.18).

**Comment by DenWav** [comment]
Thanks for the report

**Comment by wherkamp** [comment]
Hey, I am really do not understand this plugin at all. But I am trying to fix it. 
Anyway line 122 CreatePaperClip Jar 
`val originalVersions = FileEntry.parse(originalBundlerRoot.resolve(FileEntry.VERSIONS_LIST))` 
originalBundlerRoot is set to the root of the system. (the absolute path) Also the version.list file is found in caches/paperweight/data/bundler
Also 
originalBundlerJar is set to  {project}/.gradle/caches/paperweight/upstreams/paper/.gradle/caches/paperweight/taskCache/extractFromBundler.jar and that file does not contain a version.list

**Comment by lynxplay** [comment]
This should have been fixed with https://github.com/PaperMC/paperweight/commit/ed3112a32c7b69937aa84dc2ae149cd9bab76917

**Comment by wherkamp** [comment]
> This should have been fixed with [ed3112a](https://github.com/PaperMC/paperweight/commit/ed3112a32c7b69937aa84dc2ae149cd9bab76917)

I am tested that code against Purpur and it is still failing
`> java.nio.file.NoSuchFileException: /META-INF/versions.list`

**Comment by lynxplay** [comment]
You would need to wait for paper to adopt this change. When initializing the paper repo as upstreams for forks, the vanillaJar is written into a JSON file. While your fork may already use the snapshot including the fix, the paper repo that is fetched does not and hence still writes the old (and incorrect) vanillaJar location (the extracted jar).

**Comment by lynxplay** [comment]
Closed by ed3112a, for anyone still experiencing this issue please wait for paper to include paperweight `1.3.1`.
If this issue still exists after paperweight releases `1.3.1`, paper updated to that paperweight version and your fork references that new ref of paper, feel free to comment so we can investigate more :+1:

**Comment by kev626** [comment]
I can confirm that this will definitely be fixed once paper updates to 1.3.1. Thanks!
